name: Code Formatting

on:
  push:
  pull_request:

jobs:
  check_code_format:
    name: "Garante que o código esteja corretamente formatado"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - name: "Garante que o gcc-10 e g++-10 estejam instalados"
        run: |
          sudo apt install -y gcc-10 g++-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10

      - name: "Instala clang-format"
        run: sudo apt-get install -y clang-format-14

      - name: "Confere a formatação recursivamente para todos os arquivos .cpp e .hpp"
        run: find . \( -name "*.cpp" -o -name "*.hpp" \) -exec clang-format \
          --style=file:$GITHUB_WORKSPACE/.clang-format.yaml \
          --Werror \
          --dry-run {} +
        
  check_code_linting:
    name: "Garante que o código esteja seguindo os padrões definidos na guia de contribuição"
    runs-on: "ubuntu-latest"
    steps:
        - uses: actions/checkout@v4

        - name: "Garante que o gcc-10 e g++-10 estejam instalados"
          run: |
            sudo apt install gcc-10 g++-10
            sudo update-alternatives --set gcc /usr/bin/gcc-10

        - run: sudo apt-get update

        - name: "Instala o bear"
          run: sudo apt-get install bear

        - name: "Instala o clang-tidy"
          run: |
            sudo apt-get install -y clang-tidy-14
            sudo update-alternatives --set clang-tidy /usr/bin/clang-tidy-14
            clang-tidy --version

        - name: "Configura o bear"
          run: |
            chmod +x ./tidy.sh
            ./tidy.sh
            ls ./build

        - name: "Garante que os padrões de código exigidos estejam sendo seguidos"
          run: find . \( -name "*.cpp" -o -name "*.hpp" \) -exec clang-tidy \
            --config-file=$GITHUB_WORKSPACE/.clang-tidy.yaml \
            -p=$GITHUB_WORKSPACE/build \
            --header-filter=.* \
            --quiet \
            --warnings-as-errors=* {} +

        - name: "Mostra os arquivos para debugar"
          run: |
            ls
            echo
            ls src
            echo
            ls build
            echo
            pwd
